name: DjangoRESTFUL
channels:
  - defaults
dependencies:
  - pip=10.0.1
  - python=3.6
  - numpy==1.14.3
  - pandas==0.23.0
  - pip:
    - cx-oracle==6.3.1
    - django==2.0.5
    - django-cors-headers==2.2.0
    - djangorestframework==3.8.2
    - python-dateutil==2.7.3
    - pytz==2018.4
    - six==1.11.0

